### ISSUE TITLE
This plugin can not run in gitbucket 3.2

### ISSUE THREAD

**Issue by douglarek** [takezoe/gitbucket-gist-plugin#3]
When I upgraded to gitbucket 3.2, I got this:

```
2015-05-07 23:06:14.617:INFO:oejs.Server:jetty-8.y.z-SNAPSHOT
2015-05-07 23:06:14.677:INFO:oejw.WebInfConfiguration:Extract jar:file:/root/gitbucket.war!/ to /root/.gitbucket/tmp/webapp
2015-05-07 23:06:19.937:INFO:oejw.StandardDescriptorProcessor:NO JSP Support for /git, did not find org.apache.jasper.servlet.JspServlet
May 07, 2015 11:06:20 PM com.mchange.v2.log.slf4j.Slf4jMLog$Slf4jMLogger$InfoLogger log
INFO: MLog clients using slf4j logging.
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier '/mchange-commons.properties' could not be found. Skipping.", exception -> java.io.FileNotFoundException: Resource not found at path '/mchange-commons.properties'.]
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier '/mchange-log.properties' could not be found. Skipping.", exception -> java.io.FileNotFoundException: Resource not found at path '/mchange-log.properties'.]
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier '/c3p0.properties' could not be found. Skipping.", exception -> java.io.FileNotFoundException: Resource not found at path '/c3p0.properties'.]
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier '/mchange-commons.properties' could not be found. Skipping.", exception -> java.io.FileNotFoundException: Resource not found at path '/mchange-commons.properties'.]
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier '/mchange-log.properties' could not be found. Skipping.", exception -> java.io.FileNotFoundException: Resource not found at path '/mchange-log.properties'.]
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier '/c3p0.properties' could not be found. Skipping.", exception -> java.io.FileNotFoundException: Resource not found at path '/c3p0.properties'.]
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "Missing or empty HOCON configuration for resource path 'application'.", exception -> null]
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "Missing or empty HOCON configuration for resource path 'c3p0'.", exception -> null]
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "Value at path 'akka.actor.deployment.default.routees.paths' could not be converted to a String. Skipping.", exception -> null]
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "Value at path 'akka.loggers' could not be converted to a String. Skipping.", exception -> null]
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "Value at path 'akka.extensions' could not be converted to a String. Skipping.", exception -> null]
May 07, 2015 11:06:20 PM com.mchange.v2.log.slf4j.Slf4jMLog$Slf4jMLogger$InfoLogger log
INFO: Initializing c3p0-0.9.1.1 [built 15-March-2007 01:32:31; debug? true; trace: 10]
May 07, 2015 11:06:21 PM com.mchange.v2.log.slf4j.Slf4jMLog$Slf4jMLogger$InfoLogger log
INFO: Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, dataSourceName -> z8kfsx99dqbl9ornop78|ff32798, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.h2.Driver, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, identityToken -> z8kfsx99dqbl9ornop78|ff32798, idleConnectionTestPeriod -> 0, initialPoolSize -> 3, jdbcUrl -> jdbc:h2:/root/.gitbucket/data;MVCC=true, lastAcquisitionFailureDefaultUser -> null, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, numThreadsAwaitingCheckoutDefaultUser -> 0, preferredTestQuery -> null, properties -> {user=******, password=******}, propertyCycle -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false ]
2015-05-07 23:06:21.762:WARN:oejuc.AbstractLifeCycle:FAILED o.e.j.w.WebAppContext{/git,file:/root/.gitbucket/tmp/webapp/},file:/root/gitbucket.war: java.lang.AbstractMethodError: Plugin.initialize(Lgitbucket/core/plugin/PluginRegistry;Ljavax/servlet/ServletContext;Lgitbucket/core/service/SystemSettingsService$SystemSettings;)V
java.lang.AbstractMethodError: Plugin.initialize(Lgitbucket/core/plugin/PluginRegistry;Ljavax/servlet/ServletContext;Lgitbucket/core/service/SystemSettingsService$SystemSettings;)V
	at gitbucket.core.plugin.PluginRegistry$$anonfun$initialize$1.apply(PluginRegistory.scala:123)
	at gitbucket.core.plugin.PluginRegistry$$anonfun$initialize$1.apply(PluginRegistory.scala:98)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistory.scala:98)
	at gitbucket.core.servlet.InitializeListener$$anonfun$contextInitialized$1.apply(InitializeListener.scala:41)
	at gitbucket.core.servlet.InitializeListener$$anonfun$contextInitialized$1.apply(InitializeListener.scala:30)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.apply(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:426)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withTransaction(JdbcBackend.scala:46)
	at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:30)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:782)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:424)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:774)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at JettyLauncher.main(JettyLauncher.java:65)
2015-05-07 23:06:21.765:WARN:oejuc.AbstractLifeCycle:FAILED org.eclipse.jetty.server.Server@793903f1: java.lang.AbstractMethodError: Plugin.initialize(Lgitbucket/core/plugin/PluginRegistry;Ljavax/servlet/ServletContext;Lgitbucket/core/service/SystemSettingsService$SystemSettings;)V
java.lang.AbstractMethodError: Plugin.initialize(Lgitbucket/core/plugin/PluginRegistry;Ljavax/servlet/ServletContext;Lgitbucket/core/service/SystemSettingsService$SystemSettings;)V
	at gitbucket.core.plugin.PluginRegistry$$anonfun$initialize$1.apply(PluginRegistory.scala:123)
	at gitbucket.core.plugin.PluginRegistry$$anonfun$initialize$1.apply(PluginRegistory.scala:98)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistory.scala:98)
	at gitbucket.core.servlet.InitializeListener$$anonfun$contextInitialized$1.apply(InitializeListener.scala:41)
	at gitbucket.core.servlet.InitializeListener$$anonfun$contextInitialized$1.apply(InitializeListener.scala:30)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.apply(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:426)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withTransaction(JdbcBackend.scala:46)
	at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:30)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:782)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:424)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:774)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at JettyLauncher.main(JettyLauncher.java:65)
Exception in thread "main" java.lang.AbstractMethodError: Plugin.initialize(Lgitbucket/core/plugin/PluginRegistry;Ljavax/servlet/ServletContext;Lgitbucket/core/service/SystemSettingsService$SystemSettings;)V
	at gitbucket.core.plugin.PluginRegistry$$anonfun$initialize$1.apply(PluginRegistory.scala:123)
	at gitbucket.core.plugin.PluginRegistry$$anonfun$initialize$1.apply(PluginRegistory.scala:98)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistory.scala:98)
	at gitbucket.core.servlet.InitializeListener$$anonfun$contextInitialized$1.apply(InitializeListener.scala:41)
	at gitbucket.core.servlet.InitializeListener$$anonfun$contextInitialized$1.apply(InitializeListener.scala:30)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.apply(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:426)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withTransaction(JdbcBackend.scala:46)
	at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:30)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:782)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:424)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:774)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at JettyLauncher.main(JettyLauncher.java:65)
```

**Comment by takezoe** [comment]
Fixed in #4
